# -*- coding: utf-8 -*-
"""veriBilimiProjeOdevi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QQrnd-6TEewO2l3UxUlj0IBpBvqI4rww
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score

# Veriyi yükle
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/communities/communities.data"
df = pd.read_csv(url, header=None, na_values="?")

# Gereksiz ilk 5 sütunu at ve çok fazla eksik veri içeren sütunları temizle
df.drop(columns=[0, 1, 2, 3, 4], inplace=True)
df.dropna(axis=1, inplace=True)

# Hedef değişken son sütundur (ViolentCrimesPerPop)
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

# Eğitim ve test setlerine ayır
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Ölçeklendirme (Özellikle YSA, CNN ve Lineer Regresyon için kritik)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

results = {} # Sonuçları burada toplayacağız

print("Veri hazırlandı.")

from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_train_scaled, y_train)
y_pred = lr.predict(X_test_scaled)

results['Lineer Regresyon'] = r2_score(y_test, y_pred)

plt.figure(figsize=(6,4))
plt.scatter(y_test, y_pred, alpha=0.5, color='purple')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--')
plt.title("Lineer Regresyon: Gerçek vs Tahmin")
plt.show()

from sklearn.tree import DecisionTreeRegressor

dt = DecisionTreeRegressor(random_state=42)
dt.fit(X_train, y_train)
y_pred = dt.predict(X_test)

results['Karar Ağacı'] = r2_score(y_test, y_pred)

plt.figure(figsize=(6,4))
plt.scatter(y_test, y_pred, alpha=0.5, color='purple')
plt.title("Karar Ağacı: Gerçek vs Tahmin")
plt.show()

from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

results['Rastgele Orman'] = r2_score(y_test, y_pred)

plt.figure(figsize=(6,4))
sns.histplot(y_test - y_pred, kde=True, color='pink')
plt.title("Rastgele Orman: Hata Dağılımı")
plt.show()

from sklearn.neighbors import KNeighborsRegressor

knn = KNeighborsRegressor(n_neighbors=5)
knn.fit(X_train_scaled, y_train)
y_pred = knn.predict(X_test_scaled)

results['K-En Yakın Komşu'] = r2_score(y_test, y_pred)

plt.figure(figsize=(6,4))
plt.plot(y_test.values[:50], label="Gerçek", marker='o' , color='purple')
plt.plot(y_pred[:50], label="Tahmin", marker='x',color='midnightblue')
plt.title("KNN: İlk 50 Örnek Tahmin Kıyaslaması")
plt.legend()
plt.show()

from sklearn.linear_model import BayesianRidge

br = BayesianRidge()
br.fit(X_train_scaled, y_train)
y_pred = br.predict(X_test_scaled)

results['Basit Bayes (Bayesian Ridge)'] = r2_score(y_test, y_pred)

plt.figure(figsize=(6,4))
sns.regplot(x=y_test, y=y_pred, scatter_kws={'alpha':0.3}, line_kws={'color':'purple'})
plt.title("Bayesian Ridge Regresyonu")
plt.show()

from sklearn.neural_network import MLPRegressor

mlp = MLPRegressor(hidden_layer_sizes=(64, 32), max_iter=500, random_state=42)
mlp.fit(X_train_scaled, y_train)
y_pred = mlp.predict(X_test_scaled)

results['YSA (MLP)'] = r2_score(y_test, y_pred)

plt.figure(figsize=(6,4))
plt.plot(mlp.loss_curve_,color='purple')
plt.title("YSA Eğitim Kayıp (Loss) Eğrisi")
plt.xlabel("Iterasyon")
plt.ylabel("Kayıp")
plt.show()

import tensorflow as tf
from tensorflow.keras import layers, models

# CNN için veriyi şekillendirme (Samples, Features, 1)
X_train_cnn = X_train_scaled.reshape(X_train_scaled.shape[0], X_train_scaled.shape[1], 1)
X_test_cnn = X_test_scaled.reshape(X_test_scaled.shape[0], X_test_scaled.shape[1], 1)

model = models.Sequential([
    layers.Conv1D(32, 3, activation='relu', input_shape=(X_train_scaled.shape[1], 1)),
    layers.MaxPooling1D(2),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(1)
])

model.compile(optimizer='adam', loss='mse')
history = model.fit(X_train_cnn, y_train, epochs=20, batch_size=32, verbose=0)

y_pred = model.predict(X_test_cnn).flatten()
results['CNN'] = r2_score(y_test, y_pred)

plt.figure(figsize=(6,4))
plt.plot(history.history['loss'],color='purple')
plt.title("CNN Eğitim Kaybı")
plt.show()

# Sonuç Tablosu
final_df = pd.DataFrame(list(results.items()), columns=['Değerlendirme Kriterleri', 'Tahmin Oranı (R2)'])

# Tabloyu başarı sırasına göre diz
final_df = final_df.sort_values(by='Tahmin Oranı (R2)', ascending=False).reset_index(drop=True)

print("Tablo 1. Elde edilen sonuçlar")
print("-" * 50)
print(final_df)